# Generated by Django 5.2.17 on 2026-09-15 09:41

import django.db.models.deletion
import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='GuideSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\uc218\uc815 \uc2dc\uac01')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='\uc124\uba85 ID')),
                ('title', models.CharField(max_length=240, verbose_name='\uc81c\ubaa9')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '\ubb38\uc11c \uc81c\ubaa9'), (2, '\ubd84\ub958'), (3, '\uac74\ubb3c \uc124\uba85')], default=3, verbose_name='\uc81c\ubaa9 \ub2e8\uacc4')),
                ('body', models.TextField(blank=True, help_text='\ubb38\ub2e8\xb7\ubaa9\ub85d\xb7\ud45c\xb7\ub9c1\ud06c\ub97c Markdown\uc73c\ub85c \uc791\uc131\ud569\ub2c8\ub2e4. HTML\uc740 \ud45c\uc2dc\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.', verbose_name='\uc0c1\uc138 \uc124\uba85')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='\ud45c\uc2dc \uc21c\uc11c')),
                ('published', models.BooleanField(default=False, verbose_name='\uacf5\uac1c')),
            ],
            options={
                'verbose_name': '\uc0c1\uc138 \uc124\uba85',
                'verbose_name_plural': '\uac74\ubb3c \uc0c1\uc138 \uc124\uba85\xb7\uc548\ub0b4',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\uc218\uc815 \uc2dc\uac01')),
                ('key', models.SlugField(max_length=160, unique=True, verbose_name='\ub9ac\uc18c\uc2a4 ID')),
                ('name', models.CharField(max_length=240, verbose_name='\uc774\ub984')),
                ('kind', models.CharField(choices=[('model', '\uac74\ubb3c \ubaa8\ud615'), ('file', '\uacf5\uac1c \ud30c\uc77c')], max_length=20, verbose_name='\uc885\ub958')),
                ('path', models.CharField(help_text='\ubc30\ud3ec\ub41c \uacf5\uac1c \ub9ac\uc18c\uc2a4\uc758 \uc0c1\ub300 \uacbd\ub85c\uc785\ub2c8\ub2e4. \ud30c\uc77c\uc740 DB\uc5d0 \uc800\uc7a5\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.', max_length=500, verbose_name='\ub9ac\uc18c\uc2a4 \uacbd\ub85c')),
                ('renderer', models.CharField(blank=True, choices=[('box', '\uae30\ubcf8 \uc0c1\uc790'), ('city_gate', '\ub3c4\uc131 \ubb38'), ('jongmyo', '\uc885\ubb18 \uc815\uc804'), ('throne_hall', '\uad81\uad90 \uc815\uc804'), ('palace_compound', '\uad81\uad90 \uad6c\uc5ed'), ('palace_gate', '\uad81\ubb38'), ('gyeonghoeru_pond', '\uacbd\ud68c\ub8e8 \uc5f0\ubabb'), ('hall_site', '\uc804\uac01 \ud130'), ('observatory', '\uad00\uc0c1\uac10'), ('wongaksa_pagoda', '\uc6d0\uac01\uc0ac \ud0d1'), ('training_ground', '\ud6c8\ub828\uc6d0'), ('bell_tower', '\uc885\ub8e8'), ('site_marker', '\uc9d1\ud130 \ud45c\uc11d'), ('house_site', '\uc9d1\ud130 \ubaa8\ud615'), ('yukjo_compound', '\uad00\uc544')], max_length=60, verbose_name='\ubaa8\ud615 \uc0dd\uc131\uae30')),
                ('description', models.TextField(blank=True, verbose_name='\uc124\uba85')),
                ('source_url', models.URLField(blank=True, max_length=1000, validators=[webapp.models.validate_public_url], verbose_name='\ucd9c\ucc98 URL')),
                ('license', models.CharField(blank=True, max_length=300, verbose_name='\uc774\uc6a9 \uc870\uac74')),
            ],
            options={
                'verbose_name': '\ub9ac\uc18c\uc2a4',
                'verbose_name_plural': '\ub9ac\uc18c\uc2a4 \ubaa9\ub85d',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\uc218\uc815 \uc2dc\uac01')),
                ('key', models.SlugField(help_text='\uc9c0\ub3c4\xb7\uc774\uc57c\uae30 \uc5f0\uacb0\uc5d0 \uc4f0\uc774\ub294 \uace0\uc815 ID\uc785\ub2c8\ub2e4.', max_length=100, unique=True, verbose_name='\uac74\ubb3c ID')),
                ('name', models.CharField(max_length=240, verbose_name='\uc774\ub984')),
                ('category', models.CharField(max_length=80, verbose_name='\ubd84\ub958')),
                ('summary', models.TextField(blank=True, verbose_name='\uc9e7\uc740 \uc18c\uac1c')),
                ('period', models.TextField(blank=True, verbose_name='\uc874\uc7ac \uc2dc\uae30')),
                ('in_1750', models.TextField(blank=True, verbose_name='1750\ub144 \ubb34\ub835')),
                ('map_config', models.JSONField(help_text='\uc6d0\ub3c4 \uc88c\ud45c\xb7\ud06c\uae30 \ub4f1 \uc9c0\ub3c4 \ubc30\uce58 \uc124\uc815\uc785\ub2c8\ub2e4. \uace0\uae09 \ud3b8\uc9d1 \ud56d\ubaa9\uc785\ub2c8\ub2e4.', validators=[webapp.models.validate_map_config], verbose_name='\ubc30\uce58\xb7\ubaa8\ud615 \ub9e4\uac1c\ubcc0\uc218')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='\ud45c\uc2dc \uc21c\uc11c')),
                ('published', models.BooleanField(default=False, verbose_name='\uacf5\uac1c')),
                ('guide_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='webapp.guidesection', verbose_name='\uc0c1\uc138 \uc124\uba85')),
                ('model_resource', models.ForeignKey(limit_choices_to={'kind': 'model'}, on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='webapp.resource', verbose_name='\uac74\ubb3c \ubaa8\ud615')),
            ],
            options={
                'verbose_name': '\uac74\ubb3c',
                'verbose_name_plural': '\uac74\ubb3c \ubaa9\ub85d',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\uc218\uc815 \uc2dc\uac01')),
                ('key', models.SlugField(max_length=120, unique=True, verbose_name='\uc774\uc57c\uae30 ID')),
                ('target_type', models.CharField(choices=[('landmark', '\uac74\ubb3c'), ('bridge', '\ub2e4\ub9ac'), ('place', '\ub3d9\ub124')], default='landmark', max_length=20, verbose_name='\uc7a5\uc18c \uc885\ub958')),
                ('target_key', models.CharField(blank=True, help_text='\uac74\ubb3c \uc774\uc57c\uae30\uc5d0\uc11c\ub294 \ube44\uc6cc \ub461\ub2c8\ub2e4.', max_length=160, verbose_name='\ub2e4\ub9ac\xb7\ub3d9\ub124 ID')),
                ('title', models.CharField(max_length=240, verbose_name='\uc81c\ubaa9')),
                ('year', models.CharField(blank=True, max_length=80, verbose_name='\uc5f0\ub3c4')),
                ('legend', models.BooleanField(default=False, verbose_name='\uc804\ud574\uc9c0\ub294 \uc774\uc57c\uae30')),
                ('text', models.TextField(verbose_name='\ubcf8\ubb38')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='\ud45c\uc2dc \uc21c\uc11c')),
                ('published', models.BooleanField(default=False, verbose_name='\uacf5\uac1c')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='webapp.building', verbose_name='\uac74\ubb3c')),
            ],
            options={
                'verbose_name': '\uc774\uc57c\uae30',
                'verbose_name_plural': '\uc7a5\uc18c \uc774\uc57c\uae30',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='\ucd9c\ucc98 \uc774\ub984')),
                ('url', models.URLField(max_length=1500, validators=[webapp.models.validate_public_url], verbose_name='URL')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='\ud45c\uc2dc \uc21c\uc11c')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='webapp.building')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='webapp.story')),
            ],
            options={
                'verbose_name': '\ucd9c\ucc98',
                'verbose_name_plural': '\ucd9c\ucc98',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('building__isnull', False), ('target_key', ''), ('target_type', 'landmark')), models.Q(('building__isnull', True), ('target_type__in', ['bridge', 'place']), models.Q(('target_key', ''), _negated=True)), _connector='OR'), name='story_has_one_target'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('building__isnull', False), ('story__isnull', True)), models.Q(('building__isnull', True), ('story__isnull', False)), _connector='OR'), name='citation_has_one_owner'),
        ),
    ]
