# Generated by Django 5.2.17 on 2026-09-15 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(editable=False, unique=True, verbose_name='플레이어 토큰')),
                ('money', models.PositiveIntegerField(default=0, verbose_name='엽전(문)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='처음 방문')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='마지막 활동')),
            ],
            options={
                'verbose_name': '플레이어',
                'verbose_name_plural': '플레이어',
            },
        ),
        migrations.CreateModel(
            name='PlayerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=60, verbose_name='물건 ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='webapp.player')),
            ],
            options={
                'verbose_name': '봇짐 물건',
                'verbose_name_plural': '봇짐 물건',
                'constraints': [models.UniqueConstraint(fields=('player', 'item'), name='player_item_once'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='player_item_positive')],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy', '사기'), ('sell', '팔기')], max_length=4, verbose_name='거래')),
                ('shop', models.CharField(max_length=40, verbose_name='가게')),
                ('item', models.CharField(max_length=60, verbose_name='물건 ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('money_delta', models.IntegerField(verbose_name='엽전 변화')),
                ('money_after', models.PositiveIntegerField(verbose_name='거래 뒤 엽전')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='시각')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='webapp.player')),
            ],
            options={
                'verbose_name': '거래 기록',
                'verbose_name_plural': '거래 기록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['player', 'created_at'], name='webapp_trad_player__f2271d_idx')],
            },
        ),
    ]
