# Generated by Django 5.2.17 on 2026-09-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_player_economy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_key', models.CharField(db_index=True, max_length=64)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=16, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='player',
            name='name_key',
            field=models.CharField(editable=False, max_length=64, null=True, unique=True, verbose_name='이름 비교 키'),
        ),
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(blank=True, editable=False, max_length=128, verbose_name='비밀번호 해시'),
        ),
    ]
