# Generated by Django 5.2.17 on 2026-09-15 15:32

import django.core.validators
import json

from django.conf import settings
from django.db import migrations, models



ECONOMY_IMPORT_KEY = 'economy-import-v1'


def seed_goods(apps, schema_editor):
    """Copy goods and shops from gis/characters/npcs.json once; after that the database is the source."""
    Item, Shop, ContentImport = (apps.get_model('webapp', name) for name in ('Item', 'Shop', 'ContentImport'))
    if Item.objects.exists() or Shop.objects.exists():
        return
    data = json.loads((settings.BASE_DIR / 'gis/characters/npcs.json').read_text())
    items = {}
    for i, (key, row) in enumerate(data['items'].items()):
        items[key] = Item.objects.create(key=key, name=row['name'], unit=row['unit'], price=row['price'], description=row.get('desc', ''),
                                         icon_shape=row['icon']['shape'], icon_color=row['icon']['color'], use=row.get('use', ''),
                                         max_owned=row.get('max_owned'), position=i, published=True)
    for i, (key, row) in enumerate(data['shops'].items()):
        shop = Shop.objects.create(key=key, about=row.get('about', ''), position=i, published=True)
        shop.items.set([items[k] for k in row['items']])
    ContentImport.objects.get_or_create(key=ECONOMY_IMPORT_KEY, defaults={'metadata': {}})


def unseed_goods(apps, schema_editor):
    apps.get_model('webapp', 'ContentImport').objects.filter(key=ECONOMY_IMPORT_KEY).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_player_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('key', models.SlugField(help_text='봇짐·거래 기록에 쓰이는 고정 ID입니다.', max_length=60, unique=True, verbose_name='물건 ID')),
                ('name', models.CharField(max_length=80, verbose_name='이름')),
                ('unit', models.CharField(help_text='필·쾌·두름·개 등', max_length=10, verbose_name='단위')),
                ('price', models.PositiveIntegerField(help_text='1냥 = 100문. 기록에서 확인하지 않은 놀이용 값입니다.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='값(문)')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('icon_shape', models.CharField(choices=[('bolt', '옷감 필'), ('roll', '옷감 두루마리'), ('fish', '어물'), ('reins', '고삐')], max_length=20, verbose_name='아이콘 모양')),
                ('icon_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', '#rrggbb 형식으로 입력하세요.')], verbose_name='아이콘 색')),
                ('use', models.CharField(blank=True, choices=[('', '없음'), ('mount', '말 타기')], max_length=20, verbose_name='쓰임')),
                ('max_owned', models.PositiveSmallIntegerField(blank=True, help_text='비워 두면 제한 없음', null=True, verbose_name='최대 보유 수')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='표시 순서')),
                ('published', models.BooleanField(default=True, verbose_name='공개')),
            ],
            options={
                'verbose_name': '물건',
                'verbose_name_plural': '물건·가격',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('key', models.CharField(help_text='시전 구역 이름(예: 면포전) 또는 인물 가게(말 장수)와 같아야 합니다.', max_length=60, unique=True, verbose_name='가게 이름')),
                ('about', models.TextField(blank=True, verbose_name='소개')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='표시 순서')),
                ('published', models.BooleanField(default=True, verbose_name='공개')),
                ('items', models.ManyToManyField(blank=True, related_name='shops', to='webapp.item', verbose_name='파는 물건')),
            ],
            options={
                'verbose_name': '가게',
                'verbose_name_plural': '가게',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.RunPython(seed_goods, unseed_goods),
    ]
