# Generated by Django 5.2.17 on 2026-09-16 14:59

import json

from django.conf import settings
from django.db import migrations, models



def fill_goods_english(apps, schema_editor):
    """Goods seeded by 0004 predate the English fields; copy them from gis/characters/npcs.json where still empty."""
    Item, Shop = (apps.get_model('webapp', name) for name in ('Item', 'Shop'))
    data = json.loads((settings.BASE_DIR / 'gis/characters/npcs.json').read_text())
    for item in Item.objects.all():
        row = data['items'].get(item.key)
        if row and not item.name_en:
            item.name_en, item.unit_en, item.description_en = row.get('name_en', ''), row.get('unit_en', ''), row.get('desc_en', '')
            item.save(update_fields=['name_en', 'unit_en', 'description_en'])
    for shop in Shop.objects.all():
        row = data['shops'].get(shop.key)
        if row and not shop.about_en:
            shop.about_en = row.get('about_en', '')
            shop.save(update_fields=['about_en'])

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_items_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='in_1750_en',
            field=models.TextField(blank=True, verbose_name='1750년 무렵(영어)'),
        ),
        migrations.AddField(
            model_name='building',
            name='name_en',
            field=models.CharField(blank=True, max_length=240, verbose_name='이름(영어)'),
        ),
        migrations.AddField(
            model_name='building',
            name='period_en',
            field=models.TextField(blank=True, verbose_name='존재 시기(영어)'),
        ),
        migrations.AddField(
            model_name='building',
            name='summary_en',
            field=models.TextField(blank=True, verbose_name='짧은 소개(영어)'),
        ),
        migrations.AddField(
            model_name='citation',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='출처 이름(영어)'),
        ),
        migrations.AddField(
            model_name='guidesection',
            name='body_en',
            field=models.TextField(blank=True, help_text='비워 두면 영어 화면에서도 한국어 설명을 보여 줍니다.', verbose_name='상세 설명(영어)'),
        ),
        migrations.AddField(
            model_name='guidesection',
            name='title_en',
            field=models.CharField(blank=True, max_length=240, verbose_name='제목(영어)'),
        ),
        migrations.AddField(
            model_name='item',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='설명(영어)'),
        ),
        migrations.AddField(
            model_name='item',
            name='name_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='이름(영어)'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_en',
            field=models.CharField(blank=True, max_length=20, verbose_name='단위(영어)'),
        ),
        migrations.AddField(
            model_name='shop',
            name='about_en',
            field=models.TextField(blank=True, verbose_name='소개(영어)'),
        ),
        migrations.AddField(
            model_name='story',
            name='text_en',
            field=models.TextField(blank=True, verbose_name='본문(영어)'),
        ),
        migrations.AddField(
            model_name='story',
            name='title_en',
            field=models.CharField(blank=True, max_length=240, verbose_name='제목(영어)'),
        ),
        migrations.RunPython(fill_goods_english, migrations.RunPython.noop),
    ]
