# Generated by Django 5.2.17 on 2026-09-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_english_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='renderer',
            field=models.CharField(blank=True, choices=[('landmark_1907', '1907\ub144 \uac74\ucd95\ubb3c'), ('box', '\uae30\ubcf8 \uc0c1\uc790'), ('city_gate', '\ub3c4\uc131 \ubb38'), ('jongmyo', '\uc885\ubb18 \uc815\uc804'), ('throne_hall', '\uad81\uad90 \uc815\uc804'), ('palace_compound', '\uad81\uad90 \uad6c\uc5ed'), ('palace_gate', '\uad81\ubb38'), ('gyeonghoeru_pond', '\uacbd\ud68c\ub8e8 \uc5f0\ubabb'), ('hall_site', '\uc804\uac01 \ud130'), ('observatory', '\uad00\uc0c1\uac10'), ('wongaksa_pagoda', '\uc6d0\uac01\uc0ac \ud0d1'), ('training_ground', '\ud6c8\ub828\uc6d0'), ('bell_tower', '\uc885\ub8e8'), ('site_marker', '\uc9d1\ud130 \ud45c\uc11d'), ('house_site', '\uc9d1\ud130 \ubaa8\ud615'), ('yukjo_compound', '\uad00\uc544')], max_length=60, verbose_name='\ubaa8\ud615 \uc0dd\uc131\uae30'),
        ),
    ]
