# Generated by Django 5.2.17 on 2026-09-20 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_scene_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='icon_shape',
            field=models.CharField(choices=[('bolt', '옷감 필'), ('roll', '옷감 두루마리'), ('fish', '어물'), ('reins', '고삐'), ('rod', '낚싯대')], max_length=20, verbose_name='아이콘 모양'),
        ),
        migrations.AlterField(
            model_name='item',
            name='use',
            field=models.CharField(blank=True, choices=[('', '없음'), ('mount', '말 타기'), ('fish', '낚시')], max_length=20, verbose_name='쓰임'),
        ),
        migrations.CreateModel(
            name='FishingCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(unique=True)),
                ('era', models.PositiveSmallIntegerField()),
                ('ready_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('waiting', '기다림'), ('finished', '완료'), ('cancelled', '취소')], max_length=12)),
                ('caught', models.BooleanField(default=False)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fishing_cast', to='webapp.player')),
            ],
        ),
    ]
