# Generated by Django 5.2.17 on 2026-09-20 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_fishing_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='icon_shape',
            field=models.CharField(choices=[('bolt', '옷감 필'), ('roll', '옷감 두루마리'), ('fish', '어물'), ('reins', '고삐'), ('rod', '낚싯대'), ('herb', '약초')], max_length=20, verbose_name='아이콘 모양'),
        ),
        migrations.CreateModel(
            name='HerbHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=30)),
                ('next_at', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herb_harvests', to='webapp.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'node'), name='herb_harvest_once')],
            },
        ),
    ]
