# Generated by Django 5.2.17 on 2026-09-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_herb_harvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingcast',
            name='item',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
