# Generated by Django 5.2.17 on 2026-09-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_fishing_catch_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='icon_shape',
            field=models.CharField(choices=[('bolt', '옷감 필'), ('roll', '옷감 두루마리'), ('fish', '어물'), ('reins', '고삐'), ('rod', '낚싯대'), ('herb', '약초'), ('book', '책')], max_length=20, verbose_name='아이콘 모양'),
        ),
    ]
