# Generated by Django 5.2.17 on 2026-09-20 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_book_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.SlugField(max_length=100)),
                ('definition_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('new', '미시작'), ('active', '진행 중'), ('completed', '완료')], default='new', max_length=12)),
                ('checkpoint', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_events', to='webapp.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'event_id'), name='one_historical_event_per_player')],
            },
        ),
    ]
