# Generated by Django 5.2.17 on 2026-09-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_historical_event_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='action_bar',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='action_bar_revision',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
