# Generated by Django 5.2.17 on 2026-09-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_account_action_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='use',
            field=models.CharField(blank=True, choices=[('', '없음'), ('mount', '말 타기'), ('fish', '낚시'), ('flashback', '회상 진입')], max_length=20, verbose_name='쓰임'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='renderer',
            field=models.CharField(blank=True, choices=[('landmark_1907', '1907년 건축물'), ('box', '기본 상자'), ('city_gate', '도성 문'), ('jongmyo', '종묘 정전'), ('throne_hall', '궁궐 정전'), ('palace_compound', '궁궐 구역'), ('palace_gate', '궁문'), ('gyeonghoeru_pond', '경회루 연못'), ('hall_site', '전각 터'), ('observatory', '관상감'), ('wongaksa_pagoda', '원각사 탑'), ('training_ground', '훈련원'), ('bell_tower', '종루'), ('site_marker', '집터 표석'), ('house_site', '집터 모형'), ('walled_garden', '담장 원유'), ('yukjo_compound', '관아')], max_length=60, verbose_name='모형 생성기'),
        ),
    ]
