# Generated by Django 5.2.17 on 2026-09-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_item_use_flashback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='in_1750',
            field=models.TextField(blank=True, verbose_name='1750년대 중엽'),
        ),
        migrations.AlterField(
            model_name='building',
            name='in_1750_en',
            field=models.TextField(blank=True, verbose_name='1750년대 중엽(영어)'),
        ),
    ]
